APP_RUNNNIG: true
DISCORD_CHANNEL_ID: "943008506397749258"
OPENAI_ENDPOINT: https://api.openai.com/v1
account_to_query: axelofwar
ada: text-ada-001
babbage: text-babbage-001
curie: text-curie-001
davinci: text-davinci-003
data_channel_id: "943008506397749258"
chat_channel_id: "943003619949690941"
discord_channel_id_2: "943011412219920415"
max_tokens: 150
prompt: "What has Axelofwar been up to lately?"
temp: 0.9
timeout: 5
tweet_history: 15
