# Generated by Django 4.1.5 on 2023-03-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('favorites', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('replies', models.IntegerField()),
                ('impressions', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'pfp_table',
                'db_table': 'pfp_table',
            },
        ),
    ]
