# Generated by Django 4.1.5 on 2023-03-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='favorites',
            new_name='Favorites',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='impressions',
            new_name='Impressions',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='author',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='replies',
            new_name='Replies',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='retweets',
            new_name='Retweets',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='index',
            field=models.CharField(default='defaultUser', max_length=255, primary_key=True, serialize=False),
        ),
    ]
